development:
  host: 'localhost'
  adapter: 'postgresql'
  database: 'week-four-library'
  encoding: 'utf8'
  pool: 5
  username: patrick
  password: patrick
test:
  host: 'localhost'
  adapter: 'postgresql'
  database: 'week-four-library-test'
  encoding: 'utf8'
  pool: 5
  username: patrick
  password: patrick
